### PR TITLE
Add Chinese Translation

### PR DESCRIPTION
**Pull request by redpanda3**

### CODE REVIEW

**Comment by schoeberl** [comment]
Thank you for all your work. However, I think it makes sense to keep the English and Chinese version in its own repositories.

**Comment by redpanda3** [comment]
Sorry for the long delay. I had a stroke last week. Here is the updated version of Chinese translation tex. Please have a check.

**Comment by schoeberl** [comment]
Wow, a stroke! Wish you all the best for recovery!

Take care,
Martin

**Comment by schoeberl** [comment]
I can add chisel-book_chinese.tex if you want to host it in this repo. However, your pull request contains 300 files, where most probably should not be there (it even includes generated files).

Please do a new pull request with just the minimal change needed to build the book.

Thanks,
Martin

**Pull request closed without merging**
